<br>
<a href="#simple_patch">Creating a simple patchwork</a><br>
<a href="#playing">Playing with the patchwork</a><br>
<a href="#building">Compiling patchwork13</a><br>
coming soon:<br> 
creating your own patch <br>
<br><br><br>
<h2><a name="simple_patch">Creating a simple patchwork</a></h2>
<br><br>
we will create a patchork generating a sinusoidal signal and display it.
<br><br>
<h3>1) Create a new patchwork</h3><br>
  run patchwork13 : "pw13_gtk" under unix , icon under mac and windows<br>
<br>
<div align="center">
<img src="http://patchwork13.sourceforge.net/screenshots/main_window.jpg"><br />
</div>
<br><br>
  In the main window, click on :<br> 
  File&gt;new
<br><br>
  You should now see an empty patchwork :
<br><br>
<div align="center">
<img src="http://patchwork13.sourceforge.net/screenshots/patchwork.jpg"><br />
</div>
<br><br>
<h3>2) Add a patch:</h3><br>
  expand the tree by clicking on the arrow in the main window<br>
  drag the patch /std/time/augend and drop it in the patchwork window newly created ,
  The augend patch is essential in any patchwork , it increment the time .<br>
  now that you know how to add a patch , add the following patches :<br>
  <div>-/std/float/osc<br>
  this patch generates the signal<br>
  -/gtk/displays/oscilloscope<br>
  this is where we will see the signal</div>
<h3>3) Link the patches</h3><br>
  for the moment the patchwork should not work<br>
  the only thing we need is to link the patches<br><br>
   
  1-link "t" on augend to "next time" on Master ,by draging and dropping from the first to the second<br><br>
  
  2-link "void" on oscilloscope 1 to "'a" on Master<br><br>
  
  3-link "osc" on osc 1 to "Signal" on oscilloscope 1 <br><br>

<h3>
4) Run the pachwork</h3><br>
  click on play<br><br>
Here is the result that shoud be displayed on your screen... Enjoy !<br>
(note that we have added a patch 'float 1' to be able to change the frequency of the oscillations)<br>
<div align="center">
<img src="http://patchwork13.sourceforge.net/screenshots/oscillator.jpg"><br />
</div>
<br><br>
<h2><a name="playing">Playing with the patchwork</a></h2><br><br>

we will use the preceding patchwork to play<br><br>

<h3>1) Time</h3><br>
 most of the time you will create a system evoluating in the time, 
in patchwork the time evolution is controled by "augend" (/std/time/augend).
each time the job is finished, the time is incremented with "dt",
and the the job is restarted, in fact this is not real time.
you can modify "dt" by linking the output of a patch giving a float 
number (yes ,type is sensitive)<br><br>
example:
     <div>-drop the patch /gtk/const/float in the patchwork<br>
          -click on Fader in the patch "float 1" this way you can see the exact value you give<br>
          -link "k" on float 1 to "dt" on augend 1<br>
          -now test and modify the value of dt to see the effect</div>

 as you can see ,the signal generated by osc 1 changes, osc patchs use the time variable to generate the output, 
in fact all the patchs contain the time variable and give it to their neighbor ,it explains why we need to connect all the
patchs. When we connected "void" on oscilloscope 1 to "'a" on Master , it is only to maintain this chain, this way augend gives
the time to Master, it passes it to oscilloscope 1 that pass it to osc 1.<br>
<h2><a name="building">Compiling Patchwork13</a></h2>
<h3>1) Download</h3>
once downloaded , decompress the file
<PRE># tar xzfv patchwork13.tar.gz</PRE>
<h3>2) Compile</h3>
<PRE># cd patchork13</PRE>
<PRE># make</PRE>
<h3>3) Install</h3>
<PRE># make install</PRE>
<h3>4) Troubles</h3>
there is different possibilities :<br>
- the preffix is wrong<br>
- you need certain packages<br>
if the preffix is wrong :
<PRE>#make clean<br>
# rm prefix-install<br>
# make</PRE>
give the appropriate preffix
