
all: charges rapport1 rapport2 rapport3

charges:
	cd cahier_des_charges && make

rapport1:
	cd rapport_soutenance_1 && make

rapport2:
	cd rapport_soutenance_2 && make

rapport3:
	cd rapport_soutenance_3 && make

rapport4:
	cd rapport_soutenance_4 && make
